//! Per-worktree `.env.local` generator.
//!
//! Reads `<worktree>/.env` (optional) and `<worktree>/.oxyris/.env.template`
//! (required), merges them with template-wins semantics, expands `OXYRIS_*`
//! placeholders, and writes the result to `<worktree>/.env.local` with a
//! sentinel header. Existing `.env.local` files without our header are
//! treated as user-owned and never overwritten.

use std::collections::HashMap;

use oxyris_core::{AggregateId, Environment};
use oxyris_git::dotenv::Dotenv;
use oxyris_ipc::ops::{FsReadArgs, FsStatArgs, FsStatResult, FsWriteArgs, op_name};
use serde::Serialize;

use crate::infra::agent_pool::{AgentError, AgentPool};
use crate::infra::env_template;

const TEMPLATE_RELATIVE: &str = ".oxyris/.env.template";
const BASE_RELATIVE: &str = ".env";
const OUTPUT_RELATIVE: &str = ".env.local";
const HEADER_MARKER: &str = "# oxyris:dotenv-managed";

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RenderOutcome {
    /// `.env.local` was written / refreshed.
    Generated { path: String, byte_count: usize },
    /// No template found — nothing to do.
    NoTemplate,
    /// Existing `.env.local` lacks our sentinel; user owns it. Skipped.
    ManualOverride { path: String },
}

#[derive(Debug, Clone, Serialize)]
pub struct DotenvStatus {
    pub has_template: bool,
    pub has_local: bool,
    /// True when both files exist AND the template was modified after the
    /// `.env.local` we generated. UI shows a "regenerate" hint.
    pub stale: bool,
    /// True when `.env.local` exists without our sentinel header — user owns it.
    pub manual_override: bool,
    pub template_path: Option<String>,
    pub local_path: Option<String>,
    pub template_modified_secs: Option<i64>,
    pub local_modified_secs: Option<i64>,
}

#[derive(Debug, thiserror::Error)]
pub enum RenderError {
    #[error("agent: {0}")]
    Agent(#[from] AgentError),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("serde: {0}")]
    Serde(#[from] serde_json::Error),
}

pub async fn render_for_worktree(
    env: &Environment,
    agent_pool: &AgentPool,
    worktree_id: AggregateId,
    worktree_path: &str,
) -> Result<RenderOutcome, RenderError> {
    let template_path = path_join(worktree_path, TEMPLATE_RELATIVE, env);
    let base_path = path_join(worktree_path, BASE_RELATIVE, env);
    let output_path = path_join(worktree_path, OUTPUT_RELATIVE, env);

    let template = match read_text(env, agent_pool, &template_path).await? {
        Some(t) => t,
        None => return Ok(RenderOutcome::NoTemplate),
    };

    // If .env.local exists, only overwrite it when it carries our sentinel.
    if let Some(existing) = read_text(env, agent_pool, &output_path).await?
        && !existing.starts_with(HEADER_MARKER)
    {
        return Ok(RenderOutcome::ManualOverride { path: output_path });
    }

    let base = read_text(env, agent_pool, &base_path)
        .await?
        .unwrap_or_default();

    // Build the worktree's variable map from `env_template` so the
    // `${OXYRIS_*}` placeholders in the template resolve consistently.
    let template_meta = env_template::detect(env, agent_pool, worktree_id, worktree_path).await?;
    let var_pairs = env_template::env_vars(worktree_id, template_meta.template_path.as_deref());
    let vars: HashMap<String, String> = var_pairs.into_iter().collect();

    let mut merged = Dotenv::parse(&base);
    let overlay = Dotenv::parse(&template);
    merged.merge(&overlay);
    merged.substitute(&vars);

    let header = format!(
        "{HEADER_MARKER}\n# Generated by Oxyris from .env + .oxyris/.env.template — edit either source, not this file.\n# Worktree: {} · {}\n\n",
        worktree_id,
        chrono::Utc::now().to_rfc3339()
    );
    let body = merged.render();
    let full = format!("{header}{body}");

    write_text(env, agent_pool, &output_path, &full).await?;
    Ok(RenderOutcome::Generated {
        path: output_path,
        byte_count: full.len(),
    })
}

/// Lightweight status query — checks template + local existence + mtime
/// drift so the UI can flag "stale" or "manual override" without doing a
/// full render pass.
pub async fn status_for_worktree(
    env: &Environment,
    agent_pool: &AgentPool,
    worktree_path: &str,
) -> Result<DotenvStatus, RenderError> {
    let template_path = path_join(worktree_path, TEMPLATE_RELATIVE, env);
    let output_path = path_join(worktree_path, OUTPUT_RELATIVE, env);

    let template_stat = stat(env, agent_pool, &template_path).await?;
    let local_stat = stat(env, agent_pool, &output_path).await?;

    let manual_override = if local_stat.exists {
        let body = read_text(env, agent_pool, &output_path)
            .await?
            .unwrap_or_default();
        !body.starts_with(HEADER_MARKER)
    } else {
        false
    };

    let stale = match (
        template_stat.modified_secs,
        local_stat.modified_secs,
        template_stat.exists,
        local_stat.exists,
    ) {
        (Some(t), Some(l), true, true) => t > l,
        _ => false,
    };

    Ok(DotenvStatus {
        has_template: template_stat.exists,
        has_local: local_stat.exists,
        stale,
        manual_override,
        template_path: if template_stat.exists {
            Some(template_path)
        } else {
            None
        },
        local_path: if local_stat.exists {
            Some(output_path)
        } else {
            None
        },
        template_modified_secs: template_stat.modified_secs,
        local_modified_secs: local_stat.modified_secs,
    })
}

async fn stat(
    env: &Environment,
    agent_pool: &AgentPool,
    path: &str,
) -> Result<FsStatResult, RenderError> {
    match env {
        Environment::Windows => {
            let p = std::path::Path::new(path);
            match std::fs::symlink_metadata(p) {
                Ok(md) => Ok(FsStatResult {
                    path: path.to_owned(),
                    exists: true,
                    is_dir: md.is_dir(),
                    is_file: md.is_file(),
                    is_symlink: md.file_type().is_symlink(),
                    size: if md.is_file() { Some(md.len()) } else { None },
                    modified_secs: md.modified().ok().and_then(|t| {
                        t.duration_since(std::time::UNIX_EPOCH)
                            .ok()
                            .map(|d| d.as_secs() as i64)
                    }),
                }),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(FsStatResult {
                    path: path.to_owned(),
                    exists: false,
                    is_dir: false,
                    is_file: false,
                    is_symlink: false,
                    size: None,
                    modified_secs: None,
                }),
                Err(e) => Err(e.into()),
            }
        }
        Environment::Wsl { distro } => {
            let value = agent_pool
                .call(
                    distro,
                    op_name::FS_STAT,
                    serde_json::to_value(FsStatArgs {
                        path: path.to_owned(),
                    })?,
                )
                .await?;
            Ok(serde_json::from_value(value)?)
        }
    }
}

async fn read_text(
    env: &Environment,
    agent_pool: &AgentPool,
    path: &str,
) -> Result<Option<String>, RenderError> {
    match env {
        Environment::Windows => {
            let p = std::path::Path::new(path);
            if !p.exists() {
                return Ok(None);
            }
            Ok(Some(std::fs::read_to_string(p)?))
        }
        Environment::Wsl { distro } => {
            // Best-effort: ask the agent to read; if fs.read errors with
            // "not found" semantics we treat as absent.
            let value = agent_pool
                .call(
                    distro,
                    op_name::FS_READ,
                    serde_json::to_value(FsReadArgs {
                        path: path.to_owned(),
                        max_bytes: Some(256 * 1024),
                    })?,
                )
                .await;
            match value {
                Ok(v) => Ok(v
                    .get("content")
                    .and_then(serde_json::Value::as_str)
                    .map(str::to_owned)),
                Err(AgentError::Remote { code, .. }) if code == "not_found" => Ok(None),
                Err(e) => Err(e.into()),
            }
        }
    }
}

async fn write_text(
    env: &Environment,
    agent_pool: &AgentPool,
    path: &str,
    contents: &str,
) -> Result<(), RenderError> {
    match env {
        Environment::Windows => {
            if let Some(parent) = std::path::Path::new(path).parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, contents)?;
            Ok(())
        }
        Environment::Wsl { distro } => {
            agent_pool
                .call(
                    distro,
                    op_name::FS_WRITE,
                    serde_json::to_value(FsWriteArgs {
                        path: path.to_owned(),
                        contents: contents.to_owned(),
                    })?,
                )
                .await?;
            Ok(())
        }
    }
}

fn path_join(base: &str, relative: &str, env: &Environment) -> String {
    let sep = match env {
        Environment::Windows => '\\',
        Environment::Wsl { .. } => '/',
    };
    let normalized = if matches!(env, Environment::Wsl { .. }) {
        relative.replace('\\', "/")
    } else {
        relative.replace('/', "\\")
    };
    if base.ends_with(sep) || base.ends_with('/') || base.ends_with('\\') {
        format!("{base}{normalized}")
    } else {
        format!("{base}{sep}{normalized}")
    }
}
